credentials:
  usernames:
    ice_planet:
      email: ice@planet.com
      name: Ice Planet
      password: ${oc.env:APP_PASSWORD} # To be replaced with hashed password
cookie:
  cookie_name: random_cookie_name
  key: random_signature_key # Must be string
  cookie_expiry_days: 30
leagues:
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Russia
    ru_name: Ğ Ğ¾ÑÑĞ¸Ñ
    emoji: ğŸ‡·ğŸ‡º
    squad_id: 159004
    xber_url: https://1xstavka.ru/line/football/225733-russia-premier-league
    fbref_shoots_url: https://fbref.com/en/comps/30/2022-2023/shooting/2022-2023-Russian-Premier-League-Stats
    fbref_xg_url: null
    fbref_shoots_creation_url: null
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: England
    ru_name: ĞĞ½Ğ³Ğ»Ğ¸Ñ
    emoji: ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿
    squad_id: 175618
    xber_url: https://1xstavka.ru/line/football/88637-england-premier-league
    fbref_shoots_url: null
    fbref_xg_url: null
    fbref_shoots_creation_url: null
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Spain
    ru_name: Ğ˜ÑĞ¿Ğ°Ğ½Ğ¸Ñ
    emoji: ğŸ‡ªğŸ‡¸
    squad_id: 185281
    xber_url: https://1xstavka.ru/line/football/127733-spain-la-liga
    fbref_shoots_url: null
    fbref_xg_url: null
    fbref_shoots_creation_url: null
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: France
    ru_name: Ğ¤Ñ€Ğ°Ğ½Ñ†Ğ¸Ñ
    emoji: ğŸ‡«ğŸ‡·
    squad_id: 175626
    xber_url: https://1xstavka.ru/line/football/12821-france-ligue-1
    fbref_shoots_url: null
    fbref_xg_url: null
    fbref_shoots_creation_url: null
  # - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
  #   name: Portugal
  #   ru_name: ĞŸĞ¾Ñ€Ñ‚ÑƒĞ³Ğ°Ğ»Ğ¸Ñ
  #   emoji: ğŸ‡µğŸ‡¹
  #   squad_id: 185282
  #   xber_url: https://1xstavka.ru/line/football/118663-portugal-primeira-liga
  #   fbref_shoots_url: null
  #   fbref_xg_url: null
  #   fbref_shoots_creation_url: null
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Netherlands
    ru_name: ĞĞ¸Ğ´ĞµÑ€Ğ»Ğ°Ğ½Ğ´Ñ‹
    emoji: ğŸ‡³ğŸ‡±
    squad_id: 175625
    xber_url: https://1xstavka.ru/line/football/2018750-netherlands-eredivisie
    fbref_shoots_url: null
    fbref_xg_url: null
    fbref_shoots_creation_url: null
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Turkey
    ru_name: Ğ¢ÑƒÑ€Ñ†Ğ¸Ñ
    emoji: ğŸ‡¹ğŸ‡·
    squad_id: 175622
    xber_url: https://1xstavka.ru/line/football/11113-turkey-superliga
    fbref_shoots_url: null
    fbref_xg_url: null
    fbref_shoots_creation_url: null
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Championship
    ru_name: Ğ§ĞµĞ¼Ğ¿Ğ¸Ğ¾Ğ½ÑˆĞ¸Ğ¿
    emoji: ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿
    squad_id: 175621
    xber_url: https://1xstavka.ru/line/football/105759-england-championship
    fbref_shoots_url: https://fbref.com/en/comps/10/shooting/Championship-Stats
    fbref_xg_url: null
    fbref_shoots_creation_url: null
