credentials:
  usernames:
    ice_planet:
      email: ice@planet.com
      name: Ice Planet
      password: ${oc.env:APP_PASSWORD} # To be replaced with hashed password
cookie:
  cookie_name: random_cookie_name
  key: random_signature_key # Must be string
  cookie_expiry_days: 30
leagues:
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Russia
    ru_name: Ğ Ğ¾ÑÑĞ¸Ñ
    emoji: ğŸ‡·ğŸ‡º
    squad_id: 159004
    xber_url: https://1xstavka.ru/line/football/225733-russia-premier-league
    fbref_playing_time_url: https://fbref.com/en/comps/30/shooting/Russian-Premier-League-Stats
    fbref_shooting_url: https://fbref.com/en/comps/30/shooting/Russian-Premier-League-Stats
    fbref_passing_url: null
    fbref_pass_types_url: null
    fbref_possesion_url: null
    fbref_shot_creation_url: null
    sportsmole_name: null
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: England
    ru_name: ĞĞ½Ğ³Ğ»Ğ¸Ñ
    emoji: ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿
    squad_id: 175618
    xber_url: https://1xstavka.ru/line/football/88637-england-premier-league
    fbref_shooting_url: https://fbref.com/en/comps/9/shooting/Premier-League-Stats
    fbref_passsing_url: https://fbref.com/en/comps/9/passing/Premier-League-Stats
    fbref_passing_types_url: https://fbref.com/en/comps/9/passing_types/Premier-League-Stats
    fbref_possesion_url: https://fbref.com/en/comps/9/possession/Premier-League-Stats
    sportsmole_name: "Premier League"
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Spain
    ru_name: Ğ˜ÑĞ¿Ğ°Ğ½Ğ¸Ñ
    emoji: ğŸ‡ªğŸ‡¸
    squad_id: 185281
    xber_url: https://1xstavka.ru/line/football/127733-spain-la-liga
    fbref_shooting_url: https://fbref.com/en/comps/12/shooting/La-Liga-Stats
    fbref_passing_url: null
    fbref_passing_types_url: null
    fbref_possesion_url: null
    sportsmole_name: "La Liga"
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: France
    ru_name: Ğ¤Ñ€Ğ°Ğ½Ñ†Ğ¸Ñ
    emoji: ğŸ‡«ğŸ‡·
    squad_id: 175626
    xber_url: https://1xstavka.ru/line/football/12821-france-ligue-1
    fbref_shooting_url: https://fbref.com/en/comps/13/shooting/Ligue-1-Stats
    fbref_passing_url: null
    fbref_passing_types_url: null
    fbref_possesion_url: null
    sportsmole_name: "Ligue 1"
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Portugal
    ru_name: ĞŸĞ¾Ñ€Ñ‚ÑƒĞ³Ğ°Ğ»Ğ¸Ñ
    emoji: ğŸ‡µğŸ‡¹
    squad_id: 185282
    xber_url: https://1xstavka.ru/line/football/118663-portugal-primeira-liga
    fbref_shooting_url: https://fbref.com/en/comps/32/shooting/Primeira-Liga-Stats
    fbref_passing_url: null
    fbref_passing_types_url: null
    fbref_possesion_url: null
    sportsmole_name: "Primeira Liga"
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Netherlands
    ru_name: ĞĞ¸Ğ´ĞµÑ€Ğ»Ğ°Ğ½Ğ´Ñ‹
    emoji: ğŸ‡³ğŸ‡±
    squad_id: 175625
    xber_url: https://1xstavka.ru/line/football/2018750-netherlands-eredivisie
    fbref_shooting_url: https://fbref.com/en/comps/23/shooting/Eredivisie-Stats
    fbref_passing_url: null
    fbref_passing_types_url: null
    fbref_possesion_url: null
    sportsmole_name: "Eredivisie"
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Turkey
    ru_name: Ğ¢ÑƒÑ€Ñ†Ğ¸Ñ
    emoji: ğŸ‡¹ğŸ‡·
    squad_id: 175622
    xber_url: https://1xstavka.ru/line/football/11113-turkey-superliga
    fbref_shooting_url: https://fbref.com/en/comps/26/shooting/Super-Lig-Stats
    fbref_passing_url: null
    fbref_passing_types_url: null
    fbref_possesion_url: null
    sportsmole_name: "Turkish Super Lig"
  - _target_: fantasy_helper.utils.dataclasses.LeagueInfo
    name: Championship
    ru_name: Ğ§ĞµĞ¼Ğ¿Ğ¸Ğ¾Ğ½ÑˆĞ¸Ğ¿
    emoji: ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿
    squad_id: 175621
    xber_url: https://1xstavka.ru/line/football/105759-england-championship
    fbref_shooting_url: https://fbref.com/en/comps/10/shooting/Championship-Stats
    fbref_passing_url: null
    fbref_passing_types_url: null
    fbref_possesion_url: null
    sportsmole_name: "Championship"
